"""Pydantic schemas for API request/response models."""

from aexy.schemas.developer import (
    DeveloperCreate,
    DeveloperResponse,
    DeveloperUpdate,
    SkillFingerprint,
)
from aexy.schemas.auth import GitHubAuthResponse, TokenResponse
from aexy.schemas.career import (
    CareerRoleCreate,
    CareerRoleResponse,
    CareerRoleUpdate,
    RoleRequirements,
    RoleGapAnalysis,
    RoleSuggestion,
    PromotionReadiness,
    LearningPathCreate,
    LearningPathGenerate,
    LearningPathResponse,
    LearningMilestoneResponse,
    PathProgressUpdate,
    StretchAssignment,
    TeamGapAnalysis,
    BusFactorRisk,
    RoadmapSkillAnalysis,
    GeneratedJD,
    InterviewRubric,
    HiringRequirementCreate,
    HiringRequirementResponse,
    CandidateScorecard,
    OrganizationSettingsCreate,
    OrganizationSettingsResponse,
    OrganizationSettingsUpdate,
)
from aexy.schemas.analytics import (
    # Enums
    WidgetType,
    MetricType,
    ScheduleFrequency,
    DeliveryMethod,
    ExportFormat,
    ExportType,
    ExportStatus,
    InsightType,
    RiskLevel,
    Trajectory,
    HealthGrade,
    # Report schemas
    WidgetConfig,
    ReportFilters,
    CustomReportCreate,
    CustomReportUpdate,
    CustomReportResponse,
    ReportTemplateResponse,
    ScheduledReportCreate,
    ScheduledReportUpdate,
    ScheduledReportResponse,
    # Export schemas
    ExportRequest,
    ExportJobResponse,
    # Analytics data schemas
    DateRange,
    SkillHeatmapData,
    ActivityHeatmapData,
    ProductivityTrends,
    WorkloadDistribution,
    CollaborationGraph,
    # Predictive schemas
    AttritionRiskAnalysis,
    BurnoutRiskAssessment,
    PerformanceTrajectory,
    TeamHealthAnalysis,
    PredictiveInsightResponse,
    # Request schemas
    SkillHeatmapRequest,
    ProductivityRequest,
    WorkloadRequest,
    CollaborationRequest,
    TeamHealthRequest,
)
from aexy.schemas.integrations import (
    SlackNotificationType,
    SlackCommandType,
    SlackOAuthCallback,
    SlackIntegrationResponse,
    SlackIntegrationUpdate,
    SlackMessage,
    SlackNotificationRequest,
    SlackNotificationResponse,
    SlackSlashCommand,
    SlackCommandResponse,
    SlackInteraction,
    SlackEvent,
    SlackUserMappingRequest,
    SlackUserMappingResponse,
    SlackNotificationLogResponse,
)
from aexy.schemas.ticketing import (
    # Type literals
    TicketFormAuthMode,
    TicketFormTemplateType,
    TicketStatus,
    TicketPriority,
    TicketSeverity,
    TicketFieldType,
    EscalationLevel,
    NotificationChannel,
    # Form schemas
    FieldOptionCreate,
    ValidationRules,
    ExternalMappings,
    TicketFormFieldCreate,
    TicketFormFieldUpdate,
    TicketFormFieldResponse,
    FieldReorder,
    FormDestinationConfig,
    ConditionalRule,
    FormTheme,
    TicketFormCreate,
    TicketFormUpdate,
    TicketFormResponse,
    TicketFormListResponse,
    # Public form schemas
    PublicFormResponse,
    PublicTicketSubmission,
    PublicSubmissionResponse,
    EmailVerificationRequest,
    # Ticket schemas
    TicketAttachment,
    ExternalIssue,
    TicketCreate,
    TicketUpdate,
    TicketAssign,
    TicketResponse as TicketResponseSchema,
    TicketListResponse,
    TicketFilters,
    # Comment schemas
    TicketCommentCreate,
    TicketCommentResponse,
    # SLA schemas
    BusinessHours,
    SLAConditions,
    SLAPolicyCreate,
    SLAPolicyUpdate,
    SLAPolicyResponse,
    # Escalation schemas
    EscalationRuleCreate,
    EscalationMatrixCreate,
    EscalationMatrixUpdate,
    EscalationMatrixResponse,
    TicketEscalationResponse,
    TicketStats,
    # Analytics schemas
    TicketMetricsResponse,
    AnalyticsOverview,
    VolumeMetrics,
    ResponseTimeMetrics,
    # File upload
    FileUploadResponse,
    FormTemplate,
)
from aexy.schemas.review import (
    # Enums
    ReviewCycleType,
    ReviewCycleStatus,
    IndividualReviewStatus,
    SubmissionType,
    SubmissionStatus,
    ReviewRequestStatus,
    ReviewRequestSource,
    GoalType,
    GoalPriority,
    GoalStatus,
    PeerSelectionMode,
    ContributionPeriodType,
    # Review Cycle
    ReviewCycleSettings,
    ReviewCycleCreate,
    ReviewCycleUpdate,
    ReviewCycleResponse,
    ReviewCycleDetailResponse,
    # Individual Review
    IndividualReviewCreate,
    IndividualReviewResponse,
    IndividualReviewDetailResponse,
    # Review Submission
    SelfReviewSubmission,
    SelfReviewUpdate,
    PeerReviewSubmission,
    AnonymousPeerReviewSubmission,
    ManagerReviewSubmission,
    ManagerReviewUpdate,
    ReviewSubmissionResponse,
    FinalReviewData,
    # Review Request
    PeerReviewRequest,
    PeerReviewerAssignment,
    PeerRequestResponse,
    ReviewRequestResponse,
    # Work Goal
    KeyResult,
    KeyResultCreate,
    KeyResultUpdate,
    WorkGoalCreate,
    WorkGoalUpdate,
    WorkGoalResponse,
    WorkGoalDetailResponse,
    GoalProgressUpdate,
    GoalCompletionData,
    LinkActivityRequest,
    LinkedContributionsResponse,
    GoalSuggestion,
    # Contribution
    ContributionMetrics,
    ContributionHighlight,
    ContributionSummaryCreate,
    ContributionSummaryResponse,
    ContributionSummaryRequest,
)

__all__ = [
    # Developer schemas
    "DeveloperCreate",
    "DeveloperResponse",
    "DeveloperUpdate",
    "SkillFingerprint",
    # Auth schemas
    "GitHubAuthResponse",
    "TokenResponse",
    # Career schemas
    "CareerRoleCreate",
    "CareerRoleResponse",
    "CareerRoleUpdate",
    "RoleRequirements",
    "RoleGapAnalysis",
    "RoleSuggestion",
    "PromotionReadiness",
    "LearningPathCreate",
    "LearningPathGenerate",
    "LearningPathResponse",
    "LearningMilestoneResponse",
    "PathProgressUpdate",
    "StretchAssignment",
    "TeamGapAnalysis",
    "BusFactorRisk",
    "RoadmapSkillAnalysis",
    "GeneratedJD",
    "InterviewRubric",
    "HiringRequirementCreate",
    "HiringRequirementResponse",
    "CandidateScorecard",
    "OrganizationSettingsCreate",
    "OrganizationSettingsResponse",
    "OrganizationSettingsUpdate",
    # Analytics schemas (Phase 4)
    "WidgetType",
    "MetricType",
    "ScheduleFrequency",
    "DeliveryMethod",
    "ExportFormat",
    "ExportType",
    "ExportStatus",
    "InsightType",
    "RiskLevel",
    "Trajectory",
    "HealthGrade",
    "WidgetConfig",
    "ReportFilters",
    "CustomReportCreate",
    "CustomReportUpdate",
    "CustomReportResponse",
    "ReportTemplateResponse",
    "ScheduledReportCreate",
    "ScheduledReportUpdate",
    "ScheduledReportResponse",
    "ExportRequest",
    "ExportJobResponse",
    "DateRange",
    "SkillHeatmapData",
    "ActivityHeatmapData",
    "ProductivityTrends",
    "WorkloadDistribution",
    "CollaborationGraph",
    "AttritionRiskAnalysis",
    "BurnoutRiskAssessment",
    "PerformanceTrajectory",
    "TeamHealthAnalysis",
    "PredictiveInsightResponse",
    "SkillHeatmapRequest",
    "ProductivityRequest",
    "WorkloadRequest",
    "CollaborationRequest",
    "TeamHealthRequest",
    # Integration schemas (Phase 4)
    "SlackNotificationType",
    "SlackCommandType",
    "SlackOAuthCallback",
    "SlackIntegrationResponse",
    "SlackIntegrationUpdate",
    "SlackMessage",
    "SlackNotificationRequest",
    "SlackNotificationResponse",
    "SlackSlashCommand",
    "SlackCommandResponse",
    "SlackInteraction",
    "SlackEvent",
    "SlackUserMappingRequest",
    "SlackUserMappingResponse",
    "SlackNotificationLogResponse",
    # Review schemas
    "ReviewCycleType",
    "ReviewCycleStatus",
    "IndividualReviewStatus",
    "SubmissionType",
    "SubmissionStatus",
    "ReviewRequestStatus",
    "ReviewRequestSource",
    "GoalType",
    "GoalPriority",
    "GoalStatus",
    "PeerSelectionMode",
    "ContributionPeriodType",
    "ReviewCycleSettings",
    "ReviewCycleCreate",
    "ReviewCycleUpdate",
    "ReviewCycleResponse",
    "ReviewCycleDetailResponse",
    "IndividualReviewCreate",
    "IndividualReviewResponse",
    "IndividualReviewDetailResponse",
    "SelfReviewSubmission",
    "SelfReviewUpdate",
    "PeerReviewSubmission",
    "AnonymousPeerReviewSubmission",
    "ManagerReviewSubmission",
    "ManagerReviewUpdate",
    "ReviewSubmissionResponse",
    "FinalReviewData",
    "PeerReviewRequest",
    "PeerReviewerAssignment",
    "PeerRequestResponse",
    "ReviewRequestResponse",
    "KeyResult",
    "KeyResultCreate",
    "KeyResultUpdate",
    "WorkGoalCreate",
    "WorkGoalUpdate",
    "WorkGoalResponse",
    "WorkGoalDetailResponse",
    "GoalProgressUpdate",
    "GoalCompletionData",
    "LinkActivityRequest",
    "LinkedContributionsResponse",
    "GoalSuggestion",
    "ContributionMetrics",
    "ContributionHighlight",
    "ContributionSummaryCreate",
    "ContributionSummaryResponse",
    "ContributionSummaryRequest",
    # Ticketing schemas
    "TicketFormAuthMode",
    "TicketFormTemplateType",
    "TicketStatus",
    "TicketPriority",
    "TicketFieldType",
    "FieldOptionCreate",
    "ValidationRules",
    "ExternalMappings",
    "TicketFormFieldCreate",
    "TicketFormFieldUpdate",
    "TicketFormFieldResponse",
    "FieldReorder",
    "FormDestinationConfig",
    "ConditionalRule",
    "FormTheme",
    "TicketFormCreate",
    "TicketFormUpdate",
    "TicketFormResponse",
    "TicketFormListResponse",
    "PublicFormResponse",
    "PublicTicketSubmission",
    "PublicSubmissionResponse",
    "EmailVerificationRequest",
    "TicketAttachment",
    "ExternalIssue",
    "TicketCreate",
    "TicketUpdate",
    "TicketAssign",
    "TicketResponseSchema",
    "TicketListResponse",
    "TicketFilters",
    "TicketCommentCreate",
    "TicketCommentResponse",
    "BusinessHours",
    "SLAConditions",
    "SLAPolicyCreate",
    "SLAPolicyUpdate",
    "SLAPolicyResponse",
    "TicketMetricsResponse",
    "AnalyticsOverview",
    "VolumeMetrics",
    "ResponseTimeMetrics",
    "FileUploadResponse",
    "FormTemplate",
]
