"""Database models for Aexy."""

from aexy.models.plan import Plan, PlanTier, DEFAULT_PLANS
from aexy.models.developer import Developer, GitHubConnection, GitHubInstallation, GoogleConnection
from aexy.models.billing import (
    CustomerBilling,
    Subscription,
    UsageRecord,
    UsageAggregate,
    Invoice,
    SubscriptionStatus,
    UsageType,
)
from aexy.models.activity import Commit, PullRequest, CodeReview
from aexy.models.career import (
    CareerRole,
    LearningPath,
    LearningMilestone,
    HiringRequirement,
    HiringCandidate,
    OrganizationSettings,
)
from aexy.models.analytics import (
    CustomReport,
    ScheduledReport,
    ExportJob,
    PredictiveInsight,
)
from aexy.models.integrations import (
    SlackIntegration,
    SlackNotificationLog,
    JiraIntegration,
    LinearIntegration,
)
from aexy.models.repository import (
    Organization,
    Repository,
    DeveloperRepository,
    DeveloperOrganization,
)
from aexy.models.workspace import (
    Workspace,
    WorkspaceMember,
    WorkspaceSubscription,
)
from aexy.models.team import (
    Team,
    TeamMember,
)
from aexy.models.sprint import (
    Sprint,
    SprintTask,
    SprintMetrics,
    TeamVelocity,
    SprintPlanningSession,
    SprintRetrospective,
    WorkspaceTaskStatus,
    WorkspaceCustomField,
    TaskGitHubLink,
    TaskActivity,
    TaskTemplate,
)
from aexy.models.epic import Epic
from aexy.models.story import UserStory, StoryActivity
from aexy.models.release import Release, ReleaseSprint
from aexy.models.goal import Goal, GoalProject, GoalEpic
from aexy.models.entity_activity import EntityActivity
from aexy.models.bug import Bug, BugActivity
from aexy.models.dependency import StoryDependency, TaskDependency
from aexy.models.metrics import (
    WorkItemMetrics,
    SprintPredictability,
    CycleTimePercentiles,
    FlowEfficiency,
)
from aexy.models.learning_activity import (
    LearningActivityLog,
    LearningTimeSession,
)
from aexy.models.gamification import (
    DeveloperGamification,
    Badge,
    DeveloperBadge,
    PREDEFINED_BADGES,
)
from aexy.models.review import (
    ReviewCycle,
    IndividualReview,
    ReviewSubmission,
    ReviewRequest,
    WorkGoal,
    ContributionSummary,
)
from aexy.models.notification import (
    Notification,
    NotificationPreference,
    EmailNotificationLog,
    NotificationEventType,
    DEFAULT_NOTIFICATION_PREFERENCES,
)
from aexy.models.oncall import (
    OnCallConfig,
    OnCallSchedule,
    OnCallSwapRequest,
    GoogleCalendarToken,
    SwapRequestStatus,
)
from aexy.models.documentation import (
    Document,
    DocumentVersion,
    DocumentTemplate,
    DocumentCodeLink,
    DocumentGenerationPrompt,
    CollaborationSession,
    DocumentCollaborator,
    DocumentSyncQueue,
    DocumentStatus,
    DocumentLinkType,
    DocumentPermission,
    TemplateCategory,
    SYSTEM_TEMPLATES,
)
from aexy.models.tracking import (
    DeveloperStandup,
    WorkLog,
    TimeEntry,
    Blocker,
    SlackChannelConfig,
    DeveloperActivityPattern,
    StandupSummary,
    TrackingSource,
    BlockerSeverity,
    BlockerCategory,
    BlockerStatus,
    WorkLogType,
    ChannelType,
)
from aexy.models.ticketing import (
    TicketForm,
    TicketFormField,
    Ticket,
    TicketResponse,
    TicketMetrics,
    SLAPolicy,
    EscalationMatrix,
    TicketEscalation,
    TicketFormAuthMode,
    TicketFormTemplateType,
    TicketStatus,
    TicketPriority,
    TicketSeverity,
    TicketFieldType,
    EscalationLevel,
)
from aexy.models.assessment import (
    Assessment,
    AssessmentTopic,
    Question,
    Candidate,
    AssessmentInvitation,
    AssessmentAttempt,
    QuestionSubmission,
    SubmissionEvaluation,
    ProctoringEvent,
    QuestionBank,
    QuestionAnalytics,
    AssessmentStatus,
    QuestionType,
    DifficultyLevel,
    InvitationStatus,
    AttemptStatus,
    ProctoringEventSeverity,
)
from aexy.models.crm import (
    CRMObject,
    CRMAttribute,
    CRMRecord,
    CRMRecordRelation,
    CRMNote,
    CRMList,
    CRMListEntry,
    CRMActivity,
    CRMAutomation,
    CRMAutomationRun,
    CRMSequence,
    CRMSequenceStep,
    CRMSequenceEnrollment,
    CRMWebhook,
    CRMWebhookDelivery,
    CRMObjectType,
    CRMAttributeType,
    CRMListViewType,
    CRMActivityType,
    CRMAutomationTriggerType,
    CRMAutomationActionType,
    CRMSequenceStepType,
    CRMSequenceEnrollmentStatus,
)
from aexy.models.google_integration import (
    GoogleIntegration,
    SyncedEmail,
    SyncedEmailRecordLink,
    SyncedCalendarEvent,
    SyncedCalendarEventRecordLink,
    EmailSyncCursor,
)
from aexy.models.workflow import WorkflowDefinition
from aexy.models.forms import (
    Form,
    FormField,
    FormSubmission,
    FormAutomationLink,
    FormAuthMode,
    FormTemplateType,
    FormFieldType,
    FormSubmissionStatus,
    TicketAssignmentMode,
)
from aexy.models.dashboard import DashboardPreferences
from aexy.models.role import CustomRole
from aexy.models.project import Project, ProjectMember, ProjectTeam
from aexy.models.permissions import (
    PERMISSIONS,
    ROLE_TEMPLATES,
    WIDGET_PERMISSIONS,
    PermissionCategory,
)
from aexy.models.app_definitions import (
    APP_CATALOG,
    SYSTEM_APP_BUNDLES,
    ROLE_DEFAULT_APP_ACCESS,
    AppCategory,
    get_app_list,
    get_bundle_list,
    get_default_app_access_for_role,
    validate_app_access_config,
)
from aexy.models.app_access import AppAccessTemplate, AppAccessLog, AppAccessLogAction
from aexy.models.email_marketing import (
    EmailTemplate,
    EmailCampaign,
    CampaignRecipient,
    EmailTrackingPixel,
    TrackedLink,
    LinkClick,
    HostedImage,
    CampaignAnalytics,
    WorkspaceEmailStats,
    SubscriptionCategory,
    EmailSubscriber,
    SubscriptionPreference,
    UnsubscribeEvent,
    EmailTemplateType,
    EmailTemplateCategory,
    CampaignType,
    CampaignStatus,
    RecipientStatus,
    BounceType,
    SubscriberStatus,
    UnsubscribeSource,
    SubscriptionFrequency,
    # Onboarding
    OnboardingFlow,
    OnboardingProgress,
    OnboardingMilestone,
    UserMilestoneAchievement,
    OnboardingStatus,
    # Visual Builder
    VisualTemplateBlock,
    SavedEmailDesign,
    BlockType,
)
from aexy.models.email_infrastructure import (
    EmailProvider,
    SendingDomain,
    SendingIdentity,
    DedicatedIP,
    WarmingSchedule,
    WarmingProgress,
    DomainHealth,
    ISPMetrics,
    SendingPool,
    SendingPoolMember,
    ProviderEventLog,
    EmailProviderType,
    ProviderStatus,
    DomainStatus,
    WarmingStatus,
    WarmingScheduleType,
    DomainHealthStatus,
    EventType,
    ISP_DOMAINS,
    CONSERVATIVE_SCHEDULE,
    MODERATE_SCHEDULE,
    AGGRESSIVE_SCHEDULE,
)
from aexy.models.compliance import (
    MandatoryTraining,
    TrainingAssignment,
    Certification,
    DeveloperCertification,
    LearningAuditLog,
    AssignmentStatus,
    CertificationStatus,
    AppliesTo,
    AuditActionType,
)
from aexy.models.learning_management import (
    LearningGoal,
    CourseApprovalRequest,
    LearningBudget,
    LearningBudgetTransaction,
    GoalStatus,
    GoalType,
    ApprovalStatus,
    ApprovalRequestType,
    TransactionType,
)
from aexy.models.learning_analytics import (
    LearningAnalyticsSnapshot,
    LearningReportDefinition,
    LearningReportRun,
    SnapshotType,
    ReportType,
    ReportScheduleFrequency,
    ReportRunStatus,
)
from aexy.models.learning_integrations import (
    HRIntegration,
    HRSyncLog,
    LMSIntegration,
    SCORMPackage,
    SCORMTracking,
    XAPIStatement,
    LearningCalendarIntegration,
    LearningCalendarEvent,
    HRProviderType,
    LMSProviderType,
    IntegrationStatus,
    SyncStatus,
    SCORMVersion,
    SCORMCompletionStatus,
    XAPIVerbType,
    CalendarProviderType,
)
from aexy.models.knowledge_graph import (
    KnowledgeEntity,
    KnowledgeEntityMention,
    KnowledgeRelationship,
    KnowledgeDocumentRelationship,
    KnowledgeExtractionJob,
    KnowledgeEntityType,
    KnowledgeRelationType,
    KnowledgeExtractionStatus,
    KnowledgeExtractionJobType,
)
from aexy.models.booking import (
    EventType,
    LocationType,
    UserAvailability,
    AvailabilityOverride,
    Booking,
    BookingStatus,
    PaymentStatus,
    CalendarConnection,
    CalendarProvider,
    TeamEventMember,
    AssignmentType,
    BookingWebhook,
)
from aexy.models.uptime import (
    UptimeMonitor,
    UptimeCheck,
    UptimeIncident,
    UptimeCheckType,
    UptimeMonitorStatus,
    UptimeIncidentStatus,
    UptimeErrorType,
)
from aexy.models.roadmap_voting import (
    RoadmapRequest,
    RoadmapVote,
    RoadmapComment,
)
from aexy.models.reminder import (
    Reminder,
    ReminderInstance,
    ReminderEscalation,
    ControlOwner,
    DomainTeamMapping,
    AssignmentRule,
    ReminderSuggestion,
    ReminderStatus,
    ReminderPriority,
    ReminderFrequency,
    InstanceStatus,
    ReminderEscalationLevel,
    AssignmentStrategy,
    ReminderCategory,
)

__all__ = [
    # Plan
    "Plan",
    "PlanTier",
    "DEFAULT_PLANS",
    # Billing
    "CustomerBilling",
    "Subscription",
    "UsageRecord",
    "UsageAggregate",
    "Invoice",
    "SubscriptionStatus",
    "UsageType",
    # Developer
    "Developer",
    "GitHubConnection",
    "GitHubInstallation",
    "GoogleConnection",
    # Activity
    "Commit",
    "PullRequest",
    "CodeReview",
    # Career
    "CareerRole",
    "LearningPath",
    "LearningMilestone",
    "HiringRequirement",
    "HiringCandidate",
    "OrganizationSettings",
    # Analytics (Phase 4)
    "CustomReport",
    "ScheduledReport",
    "ExportJob",
    "PredictiveInsight",
    # Integrations (Phase 4)
    "SlackIntegration",
    "SlackNotificationLog",
    "JiraIntegration",
    "LinearIntegration",
    # Repository
    "Organization",
    "Repository",
    "DeveloperRepository",
    "DeveloperOrganization",
    # Workspace
    "Workspace",
    "WorkspaceMember",
    "WorkspaceSubscription",
    # Team
    "Team",
    "TeamMember",
    # Sprint
    "Sprint",
    "SprintTask",
    "SprintMetrics",
    "TeamVelocity",
    "SprintPlanningSession",
    "SprintRetrospective",
    # Task Configuration
    "WorkspaceTaskStatus",
    "WorkspaceCustomField",
    "TaskGitHubLink",
    "TaskActivity",
    # Epic
    "Epic",
    # User Story
    "UserStory",
    "StoryActivity",
    # Release
    "Release",
    "ReleaseSprint",
    # Goal/OKR
    "Goal",
    "GoalProject",
    "GoalEpic",
    # Entity Activity/Timeline
    "EntityActivity",
    # Bug
    "Bug",
    "BugActivity",
    # Dependencies
    "StoryDependency",
    "TaskDependency",
    # Advanced Metrics
    "WorkItemMetrics",
    "SprintPredictability",
    "CycleTimePercentiles",
    "FlowEfficiency",
    # Learning Activity
    "LearningActivityLog",
    "LearningTimeSession",
    # Gamification
    "DeveloperGamification",
    "Badge",
    "DeveloperBadge",
    "PREDEFINED_BADGES",
    # Reviews
    "ReviewCycle",
    "IndividualReview",
    "ReviewSubmission",
    "ReviewRequest",
    "WorkGoal",
    "ContributionSummary",
    # Notifications
    "Notification",
    "NotificationPreference",
    "EmailNotificationLog",
    "NotificationEventType",
    "DEFAULT_NOTIFICATION_PREFERENCES",
    # On-Call
    "OnCallConfig",
    "OnCallSchedule",
    "OnCallSwapRequest",
    "GoogleCalendarToken",
    "SwapRequestStatus",
    # Documentation
    "Document",
    "DocumentVersion",
    "DocumentTemplate",
    "DocumentCodeLink",
    "DocumentGenerationPrompt",
    "CollaborationSession",
    "DocumentCollaborator",
    "DocumentSyncQueue",
    "DocumentStatus",
    "DocumentLinkType",
    "DocumentPermission",
    "TemplateCategory",
    "SYSTEM_TEMPLATES",
    # Tracking
    "DeveloperStandup",
    "WorkLog",
    "TimeEntry",
    "Blocker",
    "SlackChannelConfig",
    "DeveloperActivityPattern",
    "StandupSummary",
    "TrackingSource",
    "BlockerSeverity",
    "BlockerCategory",
    "BlockerStatus",
    "WorkLogType",
    "ChannelType",
    # Ticketing
    "TicketForm",
    "TicketFormField",
    "Ticket",
    "TicketResponse",
    "TicketMetrics",
    "SLAPolicy",
    "EscalationMatrix",
    "TicketEscalation",
    "TicketFormAuthMode",
    "TicketFormTemplateType",
    "TicketStatus",
    "TicketPriority",
    "TicketSeverity",
    "TicketFieldType",
    "EscalationLevel",
    # Assessment
    "Assessment",
    "AssessmentTopic",
    "Question",
    "Candidate",
    "AssessmentInvitation",
    "AssessmentAttempt",
    "QuestionSubmission",
    "SubmissionEvaluation",
    "ProctoringEvent",
    "QuestionBank",
    "QuestionAnalytics",
    "AssessmentStatus",
    "QuestionType",
    "DifficultyLevel",
    "InvitationStatus",
    "AttemptStatus",
    "ProctoringEventSeverity",
    # CRM
    "CRMObject",
    "CRMAttribute",
    "CRMRecord",
    "CRMRecordRelation",
    "CRMNote",
    "CRMList",
    "CRMListEntry",
    "CRMActivity",
    "CRMAutomation",
    "CRMAutomationRun",
    "CRMSequence",
    "CRMSequenceStep",
    "CRMSequenceEnrollment",
    "CRMWebhook",
    "CRMWebhookDelivery",
    "CRMObjectType",
    "CRMAttributeType",
    "CRMListViewType",
    "CRMActivityType",
    "CRMAutomationTriggerType",
    "CRMAutomationActionType",
    "CRMSequenceStepType",
    "CRMSequenceEnrollmentStatus",
    # Google Integration
    "GoogleIntegration",
    "SyncedEmail",
    "SyncedEmailRecordLink",
    "SyncedCalendarEvent",
    "SyncedCalendarEventRecordLink",
    "EmailSyncCursor",
    # Workflow
    "WorkflowDefinition",
    # Forms
    "Form",
    "FormField",
    "FormSubmission",
    "FormAutomationLink",
    "FormAuthMode",
    "FormTemplateType",
    "FormFieldType",
    "FormSubmissionStatus",
    "TicketAssignmentMode",
    # Dashboard
    "DashboardPreferences",
    # Roles & Permissions
    "CustomRole",
    "PERMISSIONS",
    "ROLE_TEMPLATES",
    "WIDGET_PERMISSIONS",
    "PermissionCategory",
    # App Access
    "AppAccessTemplate",
    "AppAccessLog",
    "AppAccessLogAction",
    "APP_CATALOG",
    "SYSTEM_APP_BUNDLES",
    "ROLE_DEFAULT_APP_ACCESS",
    "AppCategory",
    "get_app_list",
    "get_bundle_list",
    "get_default_app_access_for_role",
    "validate_app_access_config",
    # Projects
    "Project",
    "ProjectMember",
    "ProjectTeam",
    # Email Marketing
    "EmailTemplate",
    "EmailCampaign",
    "CampaignRecipient",
    "EmailTrackingPixel",
    "TrackedLink",
    "LinkClick",
    "HostedImage",
    "CampaignAnalytics",
    "WorkspaceEmailStats",
    "SubscriptionCategory",
    "EmailSubscriber",
    "SubscriptionPreference",
    "UnsubscribeEvent",
    "EmailTemplateType",
    "EmailTemplateCategory",
    "CampaignType",
    "CampaignStatus",
    "RecipientStatus",
    "BounceType",
    "SubscriberStatus",
    "UnsubscribeSource",
    "SubscriptionFrequency",
    # Email Infrastructure
    "EmailProvider",
    "SendingDomain",
    "SendingIdentity",
    "DedicatedIP",
    "WarmingSchedule",
    "WarmingProgress",
    "DomainHealth",
    "ISPMetrics",
    "SendingPool",
    "SendingPoolMember",
    "ProviderEventLog",
    "EmailProviderType",
    "ProviderStatus",
    "DomainStatus",
    "WarmingStatus",
    "WarmingScheduleType",
    "DomainHealthStatus",
    "EventType",
    "ISP_DOMAINS",
    "CONSERVATIVE_SCHEDULE",
    "MODERATE_SCHEDULE",
    "AGGRESSIVE_SCHEDULE",
    # Visual Email Builder
    "VisualTemplateBlock",
    "SavedEmailDesign",
    "BlockType",
    # Compliance & Certifications
    "MandatoryTraining",
    "TrainingAssignment",
    "Certification",
    "DeveloperCertification",
    "LearningAuditLog",
    "AssignmentStatus",
    "CertificationStatus",
    "AppliesTo",
    "AuditActionType",
    # Learning Management (Manager Controls)
    "LearningGoal",
    "CourseApprovalRequest",
    "LearningBudget",
    "LearningBudgetTransaction",
    "GoalStatus",
    "GoalType",
    "ApprovalStatus",
    "ApprovalRequestType",
    "TransactionType",
    # Learning Analytics & Reporting
    "LearningAnalyticsSnapshot",
    "LearningReportDefinition",
    "LearningReportRun",
    "SnapshotType",
    "ReportType",
    "ReportScheduleFrequency",
    "ReportRunStatus",
    # Learning Integrations
    "HRIntegration",
    "HRSyncLog",
    "LMSIntegration",
    "SCORMPackage",
    "SCORMTracking",
    "XAPIStatement",
    "LearningCalendarIntegration",
    "LearningCalendarEvent",
    "HRProviderType",
    "LMSProviderType",
    "IntegrationStatus",
    "SyncStatus",
    "SCORMVersion",
    "SCORMCompletionStatus",
    "XAPIVerbType",
    "CalendarProviderType",
    # Knowledge Graph
    "KnowledgeEntity",
    "KnowledgeEntityMention",
    "KnowledgeRelationship",
    "KnowledgeDocumentRelationship",
    "KnowledgeExtractionJob",
    "KnowledgeEntityType",
    "KnowledgeRelationType",
    "KnowledgeExtractionStatus",
    "KnowledgeExtractionJobType",
    # Booking/Calendar
    "EventType",
    "LocationType",
    "UserAvailability",
    "AvailabilityOverride",
    "Booking",
    "BookingStatus",
    "PaymentStatus",
    "CalendarConnection",
    "CalendarProvider",
    "TeamEventMember",
    "AssignmentType",
    "BookingWebhook",
    # Uptime Monitoring
    "UptimeMonitor",
    "UptimeCheck",
    "UptimeIncident",
    "UptimeCheckType",
    "UptimeMonitorStatus",
    "UptimeIncidentStatus",
    "UptimeErrorType",
    # Roadmap Voting
    "RoadmapRequest",
    "RoadmapVote",
    "RoadmapComment",
    # Reminders
    "Reminder",
    "ReminderInstance",
    "ReminderEscalation",
    "ControlOwner",
    "DomainTeamMapping",
    "AssignmentRule",
    "ReminderSuggestion",
    "ReminderStatus",
    "ReminderPriority",
    "ReminderFrequency",
    "InstanceStatus",
    "ReminderEscalationLevel",
    "AssignmentStrategy",
    "ReminderCategory",
]
