"""Database models for Aexy."""

from aexy.models.plan import Plan, PlanTier, DEFAULT_PLANS
from aexy.models.developer import Developer, GitHubConnection, GitHubInstallation, GoogleConnection
from aexy.models.billing import (
    CustomerBilling,
    Subscription,
    UsageRecord,
    UsageAggregate,
    Invoice,
    SubscriptionStatus,
    UsageType,
)
from aexy.models.activity import Commit, PullRequest, CodeReview
from aexy.models.career import (
    CareerRole,
    LearningPath,
    LearningMilestone,
    HiringRequirement,
    OrganizationSettings,
)
from aexy.models.analytics import (
    CustomReport,
    ScheduledReport,
    ExportJob,
    PredictiveInsight,
)
from aexy.models.integrations import (
    SlackIntegration,
    SlackNotificationLog,
    JiraIntegration,
    LinearIntegration,
)
from aexy.models.repository import (
    Organization,
    Repository,
    DeveloperRepository,
    DeveloperOrganization,
)
from aexy.models.workspace import (
    Workspace,
    WorkspaceMember,
    WorkspaceSubscription,
)
from aexy.models.team import (
    Team,
    TeamMember,
)
from aexy.models.sprint import (
    Sprint,
    SprintTask,
    SprintMetrics,
    TeamVelocity,
    SprintPlanningSession,
    SprintRetrospective,
    WorkspaceTaskStatus,
    WorkspaceCustomField,
    TaskGitHubLink,
    TaskActivity,
)
from aexy.models.epic import Epic
from aexy.models.learning_activity import (
    LearningActivityLog,
    LearningTimeSession,
)
from aexy.models.gamification import (
    DeveloperGamification,
    Badge,
    DeveloperBadge,
    PREDEFINED_BADGES,
)
from aexy.models.review import (
    ReviewCycle,
    IndividualReview,
    ReviewSubmission,
    ReviewRequest,
    WorkGoal,
    ContributionSummary,
)
from aexy.models.notification import (
    Notification,
    NotificationPreference,
    EmailNotificationLog,
    NotificationEventType,
    DEFAULT_NOTIFICATION_PREFERENCES,
)
from aexy.models.oncall import (
    OnCallConfig,
    OnCallSchedule,
    OnCallSwapRequest,
    GoogleCalendarToken,
    SwapRequestStatus,
)
from aexy.models.documentation import (
    Document,
    DocumentVersion,
    DocumentTemplate,
    DocumentCodeLink,
    DocumentGenerationPrompt,
    CollaborationSession,
    DocumentCollaborator,
    DocumentSyncQueue,
    DocumentStatus,
    DocumentLinkType,
    DocumentPermission,
    TemplateCategory,
    SYSTEM_TEMPLATES,
)
from aexy.models.tracking import (
    DeveloperStandup,
    WorkLog,
    TimeEntry,
    Blocker,
    SlackChannelConfig,
    DeveloperActivityPattern,
    StandupSummary,
    TrackingSource,
    BlockerSeverity,
    BlockerCategory,
    BlockerStatus,
    WorkLogType,
    ChannelType,
)
from aexy.models.ticketing import (
    TicketForm,
    TicketFormField,
    Ticket,
    TicketResponse,
    TicketMetrics,
    SLAPolicy,
    EscalationMatrix,
    TicketEscalation,
    TicketFormAuthMode,
    TicketFormTemplateType,
    TicketStatus,
    TicketPriority,
    TicketSeverity,
    TicketFieldType,
    EscalationLevel,
)
from aexy.models.assessment import (
    Assessment,
    AssessmentTopic,
    Question,
    Candidate,
    AssessmentInvitation,
    AssessmentAttempt,
    QuestionSubmission,
    SubmissionEvaluation,
    ProctoringEvent,
    QuestionBank,
    AssessmentStatus,
    QuestionType,
    DifficultyLevel,
    InvitationStatus,
    AttemptStatus,
    ProctoringEventSeverity,
)
from aexy.models.crm import (
    CRMObject,
    CRMAttribute,
    CRMRecord,
    CRMRecordRelation,
    CRMNote,
    CRMList,
    CRMListEntry,
    CRMActivity,
    CRMAutomation,
    CRMAutomationRun,
    CRMSequence,
    CRMSequenceStep,
    CRMSequenceEnrollment,
    CRMWebhook,
    CRMWebhookDelivery,
    CRMObjectType,
    CRMAttributeType,
    CRMListViewType,
    CRMActivityType,
    CRMAutomationTriggerType,
    CRMAutomationActionType,
    CRMSequenceStepType,
    CRMSequenceEnrollmentStatus,
)
from aexy.models.google_integration import (
    GoogleIntegration,
    SyncedEmail,
    SyncedEmailRecordLink,
    SyncedCalendarEvent,
    SyncedCalendarEventRecordLink,
    EmailSyncCursor,
)
from aexy.models.workflow import WorkflowDefinition
from aexy.models.forms import (
    Form,
    FormField,
    FormSubmission,
    FormAutomationLink,
    FormAuthMode,
    FormTemplateType,
    FormFieldType,
    FormSubmissionStatus,
    TicketAssignmentMode,
)

__all__ = [
    # Plan
    "Plan",
    "PlanTier",
    "DEFAULT_PLANS",
    # Billing
    "CustomerBilling",
    "Subscription",
    "UsageRecord",
    "UsageAggregate",
    "Invoice",
    "SubscriptionStatus",
    "UsageType",
    # Developer
    "Developer",
    "GitHubConnection",
    "GitHubInstallation",
    "GoogleConnection",
    # Activity
    "Commit",
    "PullRequest",
    "CodeReview",
    # Career
    "CareerRole",
    "LearningPath",
    "LearningMilestone",
    "HiringRequirement",
    "OrganizationSettings",
    # Analytics (Phase 4)
    "CustomReport",
    "ScheduledReport",
    "ExportJob",
    "PredictiveInsight",
    # Integrations (Phase 4)
    "SlackIntegration",
    "SlackNotificationLog",
    "JiraIntegration",
    "LinearIntegration",
    # Repository
    "Organization",
    "Repository",
    "DeveloperRepository",
    "DeveloperOrganization",
    # Workspace
    "Workspace",
    "WorkspaceMember",
    "WorkspaceSubscription",
    # Team
    "Team",
    "TeamMember",
    # Sprint
    "Sprint",
    "SprintTask",
    "SprintMetrics",
    "TeamVelocity",
    "SprintPlanningSession",
    "SprintRetrospective",
    # Task Configuration
    "WorkspaceTaskStatus",
    "WorkspaceCustomField",
    "TaskGitHubLink",
    "TaskActivity",
    # Epic
    "Epic",
    # Learning Activity
    "LearningActivityLog",
    "LearningTimeSession",
    # Gamification
    "DeveloperGamification",
    "Badge",
    "DeveloperBadge",
    "PREDEFINED_BADGES",
    # Reviews
    "ReviewCycle",
    "IndividualReview",
    "ReviewSubmission",
    "ReviewRequest",
    "WorkGoal",
    "ContributionSummary",
    # Notifications
    "Notification",
    "NotificationPreference",
    "EmailNotificationLog",
    "NotificationEventType",
    "DEFAULT_NOTIFICATION_PREFERENCES",
    # On-Call
    "OnCallConfig",
    "OnCallSchedule",
    "OnCallSwapRequest",
    "GoogleCalendarToken",
    "SwapRequestStatus",
    # Documentation
    "Document",
    "DocumentVersion",
    "DocumentTemplate",
    "DocumentCodeLink",
    "DocumentGenerationPrompt",
    "CollaborationSession",
    "DocumentCollaborator",
    "DocumentSyncQueue",
    "DocumentStatus",
    "DocumentLinkType",
    "DocumentPermission",
    "TemplateCategory",
    "SYSTEM_TEMPLATES",
    # Tracking
    "DeveloperStandup",
    "WorkLog",
    "TimeEntry",
    "Blocker",
    "SlackChannelConfig",
    "DeveloperActivityPattern",
    "StandupSummary",
    "TrackingSource",
    "BlockerSeverity",
    "BlockerCategory",
    "BlockerStatus",
    "WorkLogType",
    "ChannelType",
    # Ticketing
    "TicketForm",
    "TicketFormField",
    "Ticket",
    "TicketResponse",
    "TicketMetrics",
    "SLAPolicy",
    "EscalationMatrix",
    "TicketEscalation",
    "TicketFormAuthMode",
    "TicketFormTemplateType",
    "TicketStatus",
    "TicketPriority",
    "TicketSeverity",
    "TicketFieldType",
    "EscalationLevel",
    # Assessment
    "Assessment",
    "AssessmentTopic",
    "Question",
    "Candidate",
    "AssessmentInvitation",
    "AssessmentAttempt",
    "QuestionSubmission",
    "SubmissionEvaluation",
    "ProctoringEvent",
    "QuestionBank",
    "AssessmentStatus",
    "QuestionType",
    "DifficultyLevel",
    "InvitationStatus",
    "AttemptStatus",
    "ProctoringEventSeverity",
    # CRM
    "CRMObject",
    "CRMAttribute",
    "CRMRecord",
    "CRMRecordRelation",
    "CRMNote",
    "CRMList",
    "CRMListEntry",
    "CRMActivity",
    "CRMAutomation",
    "CRMAutomationRun",
    "CRMSequence",
    "CRMSequenceStep",
    "CRMSequenceEnrollment",
    "CRMWebhook",
    "CRMWebhookDelivery",
    "CRMObjectType",
    "CRMAttributeType",
    "CRMListViewType",
    "CRMActivityType",
    "CRMAutomationTriggerType",
    "CRMAutomationActionType",
    "CRMSequenceStepType",
    "CRMSequenceEnrollmentStatus",
    # Google Integration
    "GoogleIntegration",
    "SyncedEmail",
    "SyncedEmailRecordLink",
    "SyncedCalendarEvent",
    "SyncedCalendarEventRecordLink",
    "EmailSyncCursor",
    # Workflow
    "WorkflowDefinition",
    # Forms
    "Form",
    "FormField",
    "FormSubmission",
    "FormAutomationLink",
    "FormAuthMode",
    "FormTemplateType",
    "FormFieldType",
    "FormSubmissionStatus",
    "TicketAssignmentMode",
]
