"""add public project visibility

Revision ID: 61fd11a7e0ea
Revises: 
Create Date: 2026-01-28 12:27:45.210556

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '61fd11a7e0ea'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('is_public', sa.Boolean(), nullable=False))
    op.add_column('projects', sa.Column('public_slug', sa.String(length=120), nullable=True))
    op.create_index(op.f('ix_projects_is_public'), 'projects', ['is_public'], unique=False)
    op.create_index(op.f('ix_projects_public_slug'), 'projects', ['public_slug'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_projects_public_slug'), table_name='projects')
    op.drop_index(op.f('ix_projects_is_public'), table_name='projects')
    op.drop_column('projects', 'public_slug')
    op.drop_column('projects', 'is_public')
    # ### end Alembic commands ###
